# Generated by Django 4.1 on 2022-08-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
