# Generated by Django 4.1 on 2022-08-21 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='active',
        ),
    ]
